### PR TITLE
Update images to offical packages

### PR DESCRIPTION
**Pull request by kyguy**

### CODE REVIEW

**Comment by kyguy** [comment]
I am including the kaka-init changes as part of the kafka-init PR, and user operator is changed in the last file, did you mean another image?

Besides kafka-init, I understand there should be 4 images update with packages: 
1) cluster-operator
2) topic-operator, 
3) user-operator
4) kafka-base

**Comment by scholzj** [comment]
Yeah, right ... its these four. `kafka-init` seems to be missing.

**Comment by kyguy** [comment]
I've updated kafka-init jar in a previous PR so it is all set to go: https://github.com/jboss-container-images/jboss-amqstreams-1-openshift-image/blob/amqstreams10-dev/kafka-init/image.yaml#L29

Only these four images are left that need to be update

**Comment by scholzj** [comment]
Ok, great.

**Pull request merged**
